[project]
name = "microblog"
version = "1.0.0"
description = "A Flask microblog app built through Chapter 23 of Miguel Grinberg's Flask Mega-Tutorial."
readme = "README.md"
license = "MIT"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "babel",
    "email-validator",
    "elasticsearch",
    "flask",
    "flask-babel",
    "flask-httpauth",
    "flask-login",
    "flask-mail",
    "flask-migrate",
    "flask-moment",
    "flask-sqlalchemy",
    "flask-wtf",
    "langdetect",
    "pyjwt",
    "python-dotenv",
    "redis",
    "requests",
    "rq",
]

[project.optional-dependencies]
test = ["pytest", "httpie"]

[project.urls]
Documentation = "https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["app*"]

[tool.setuptools.package-data]
app = [
    "templates/*.html",
    "templates/*/*.html",
    "templates/email/*.txt",
    "static/*",
    "translations/*/LC_MESSAGES/*.po",
    "translations/*/LC_MESSAGES/*.mo",
]

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
testpaths = ["tests"]
filterwarnings = ["error"]
